### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by zi1zi** [kunheek/style-aware-discriminator#4]
您好，pytorch版本必须大于1.10.2吗

**Comment by kunheek** [comment]
Hi.
I don't know Chinese, so I am not sure if I understand your question correctly.
According to the Google translate, your question is 'does the pytorch version have to be greater than 1.10.2?'.

It will be compatible with other versions with the same api. However, since I have not tested other versions, 1.10.0 ~1.12.1 versions are recommended. These versions were tested by myself.

**Comment by zi1zi** [comment]
correct
